### PR TITLE
feat: add support for loki

### LINKED ISSUE #69: Consider implementing support for loki

### PR DESCRIPTION
**Pull request by FUSAKLA**
/resolves #69 

Adds support for validating of loki rules
and adds two new validations for LogQL expressions

 - isValidLoqQLExpression
 - logQlExpressionUesesRangeAggreagationn

Also adds some documentation, e2e tests for loki etc

Signed-off-by: Martin Chodur <m.chodur@seznam.cz>

### CODE REVIEW

**Comment by FUSAKLA** [comment]
PTAL @jmichalek132 if it makes sense to you and possibly what checks would you like to see for loki so I can say if this is the way how to approach it

**Comment by jmichalek132** [comment]
> PTAL @jmichalek132 if it makes sense to you and possibly what checks would you like to see for loki so I can say if this is the way how to approach it

This looks good to me, we are just starting to use loki internally within our team, so for now the generic validations + the query being valid and the yaml unmarshalling are the most important ones.
Down the line when we onboard other teams to use it I can imagine an useful validation  outside of the generic ones could be for e.g. validating than the  remote write config is not specified (I am not 100% sure, but I assume when it is it takes precedence over the configuration to the loki ruler itself which we might not want to allow).

**Comment by FUSAKLA** [comment]
Great :tada:

I'l merge it and would love some feedback if you could give it a try.

If merged you should be able to install it using the go install

**Comment by jmichalek132** [comment]
> Great 🎉
> 
> I'l merge it and would love some feedback if you could give it a try.
> 
> If merged you should be able to install it using the go install

I will on Monday :).

**Comment by jmichalek132** [comment]
> > Great 🎉
> > I'l merge it and would love some feedback if you could give it a try.
> > If merged you should be able to install it using the go install
> 
> I will on Monday :).

Tested today, it works nicely ;) looking forward to a release :).

**Pull request merged**
