### PR TITLE
Add validator to forbid usage of some metrics in rules

### PR DESCRIPTION
**Pull request by FUSAKLA**
~~resolves # 33~~

So it was misunderstanding, this does not resolve the issue #33, it adds other validator but still valid :)

### CODE REVIEW

**Comment by FUSAKLA** [comment]
@tizki do you think you could try it out if that makes sense this way?

**Comment by tizki** [comment]
Hi,
yes, I already have something. I'll open a PR shortly.
thanks

**Comment by FUSAKLA** [comment]
Oh, I'm sorry to hear that :/ It looks like we both went duplicating the effort. 
Definitely feel free to open the PR and can decide about the implementation then.

**Comment by tizki** [comment]
oh, I didn't notice your PR. 
anyway feel free to take whichever makes more sense.

**Comment by FUSAKLA** [comment]
I just reviewed your PR and in the end our PRs do not overlap, because I misunderstood what you requested :tada: :smile: 

This PR adds a validator to forbid using some metrics in alerts/rules

**Pull request merged**
